### PR TITLE
Unicode Output Icons Enhancement

### PR DESCRIPTION
**Pull request by daleattree**
Added class with static methods for unicode output icons

### CODE REVIEW

**Comment by mostertb** [comment]
Hi @daleattree 

This is a really cool addition! The static class you have created could potentially make a good package all by itself. Here are some general comments relating to integration with this bundle following from our discussion earlier:

### Unicode Support

With anything related to Unicode, support is always the greatest hassle. Your solution relies on the existence of the PHP JSON extension (good solution). While this extension has been bundled with the default distribution of PHP since 5.2.0, it is not always present in all environments (you have the option to compile PHP without it for example). 

Some other options for handling Unicode characters include:
- The new Unicode codepoint escape syntax in PHP 7 ([link](https://secure.php.net/manual/en/migration70.new-features.php#migration70.new-features.unicode-codepoint-escape-syntax))
- The `mb_convert_encoding()` function. The mbstring extension is not installed by default but is common
- possibly the `iconv()` function (which I think is built in)

Please would you add a check to determine which set of functionality is available and chose the best (fastest?) method for handling the Unicode encoding. I am happy to add the JSON and mbstring extensions to the composer reconsiderations.

At some stage in the future, it would be interesting to check if the shell that the Command is executing under supports unicode (possibly via the `LANGUAGE` or `LANG` environmental variables) but Im happy that is outside the scope of this PR. Config options to disable it via the `config.yml` and cli parameters would work well for this too

### Interface to functionality

As we discussed earlier, I am try to have all the user-facing  functionality of the bundle accessible through the `BaseCommand` class (ideally as protected functions).

Please would you implement a subclass of `AbstractEnhancement` to encapsulate your functionality.

The `initialize()` function of this would be a good place to check for the Unicode encoding support (so you only need to do this heavyweight check once). Then add a protected function to `BaseCommand` that will be your API for this functionality going forward (so that you have a defined way for users to access the functionality that is less likely to introduce breaking changes going forward) that calls a function on your enhancement class.

An option here is to have a `getIcon()` function returns an _Icon_ object that has the potential to implement a fluent interface like the following:

``` PHP
$icon = $this->getIcon()->exclamation()->red()->blink();
```

(Some really cool future extensions to this functionality could include blinking characters, text colour, background colour, bold, underline and strike-through)

And implement a `__toString()` function so that the user can do something like the following:

``` PHP
$this->getLogger()->emerg($icon.'Somthing really bad happened');
```

### Graceful Failure

I like that you have `trigger_error()` in your class. I dont not, however, want execution of a command to fail on account of Unicode support. In your enhancement class, please add logic for disabling the enhancement if it is not supported (without ending execution) so that under normal circumstances the `trigger_error()` will never be reached. 
If you store the enabled state in `RuntimeConfig`, you can use its `logConfigWarning()` function to log an alert that the functionality has been automatically disabled on account of a lack of unicode support

**Comment by daleattree** [comment]
Support checks have been added. If JSON is not available, decoding defaults to html_entity_decode which is built-in.

getIcon() has been added to BaseCommand

Runtime Configuration has been implemented and trigger_error removed as requested.

The method render() has been added to invoke the _toString() method as __toString() is only invoked when an object is cast to string and not just echo'ed. The render() method also flushes the icon setup, allowing you to generate the next icon using the same handler returned by getIcon().

An execution test has been added to ensure there are no fatal errors when executing icon related code.

Documentation has also been updated.

**Comment by mostertb** [comment]
HI @daleattree 

I really like what you've done. The use of `html_entity_decode()` as a widely supported feature is inspired (extra points for making the character set explicit for PHP 5.3 support). The `render()` function is also an elegant solution.

I am concerned that the user has direct access to the `IconEnhancement` class. This means that they could theoretically call internal implementation functions (like `preRun()`) which means that you can only ever put idempotent code in these and it makes the `EnhancementInterface` part of the user-facing interface. 

The solution is to put everything in `IconEnhancement` after `postRun` in its own `Icon` class.
Then have a factory method on `IconEnhancement` something like:

``` PHP
public function createIcon()
{
    return new Icon($this->getIconHandler());
}
```

Which can be accessed by the user through on `BaseCommand` something like

``` PHP
protected function getIcon()
{
     return $this->getIconEnhancement()->getIcon()
}
```

This also gives you the cool additional functionality of not requiring the `flushData()` method which then allows the user to do something like this:

``` PHP
$tick = $this->getIcon()->tick()->green();
$cross = $this->getIcon()->cross->red();
$myMessage = (($success) ? $tick : $cross).' Some cool text';
```

Then in terms of testing, we need some tests that can be run by a machine (rather than having a user look at the output) to leverage Travis CI. I think that you are in a prime position to write our first test that uses a PHPUnit data provider for your tests. You may even be able to reflect on your first class's constants for the data.
Having given it some thought, one basic test could be to check the number of bytes that are outputed when rendering is what is expected (possibly checking both terminal and log output). What do you think?  

Sorry to be sending this back to you again, but you are building a really awesome feature that is almost there

**Comment by daleattree** [comment]
All done.

render method is still available for when a user wants to output an icon
only with no accompanying text.

**Comment by mostertb** [comment]
This looks great now! Thanks

**Pull request merged**
