### PR TITLE
Feature/configurability

### PR DESCRIPTION
**Pull request by sarelvdwalt**

### CODE REVIEW

**Comment by sarelvdwalt** [comment]
As discussed over Skype, we're going to try aim for something similar to:

``` yml
afrihost_base_command:
    logger:
        handler_strategies:
            afrihost_default:
               log_file_extention: '.log.txt'
            console_stream:
                enabled: false
                line_formatter: ~
```

**Comment by johnathanmdell** [comment]
If I can give me 2 cents here, drop the afrihost_ prefix from the configuration, the bundle's name is BaseCommand and would cause unnecessary confusion.

**Comment by mostertb** [comment]
Nice pull request. The semantic configuration is something that we need.

Yes, @sarelvdwalt  that sort of approach fits in better with the goals of the project and should help prevent breaking changes to the configuration layout.

Also, would you please remove any unneeded `use` statements. The following looks like a culprit:

``` PHP
use Symfony\Component\VarDumper\VarDumper;
```

**Comment by sarelvdwalt** [comment]
Good point, @johnathanmdell, thanks - definitely dropping that

**Comment by mostertb** [comment]
@johnathanmdell  Thank you for checking in.

According to Symfony's [Best Practices for Reusable Bundles](http://symfony.com/doc/current/cookbook/bundles/best_practices.html), the name of the bundle should include the organisation name as a prefix.
The bundle is thus called: `AfrihostBaseCommandBundle` . This can be seen in  [this file](../blob/master/AfrihostBaseCommandBundle.php)

This makes the bundle alias  `afrihost_base_command` which I think in turn makes @sarelvdwalt version correct. Do you agree?

Its good to know that there are extra eyes reviewing the code. Thanks again

**Comment by johnathanmdell** [comment]
If you are going to argue semantics then no, it should be `afrihost_base_command_bundle`

**Comment by sarelvdwalt** [comment]
_sigh_ ok what are we using:
- base_command
- afrihost_base_command
- afrihost_base_command_bundle
  ?

**Comment by sarelvdwalt** [comment]
Ok gents, I've updated the PR. It includes:
- some PSR :)
- From the above it seems we're using afrihost, for now I've kept it "afrihost_base_command"
- The format of the config is now:

``` yml
afrihost_base_command:
    logger:
        handler_strategies:
            default:
                file_extention:       .log.txt
            console_stream:
                enabled:              true
```

**Comment by sarelvdwalt** [comment]
When you don't specify `->addDefaultsIfNotSet()` to an addayNode, then it won't be in your config unless you overwrote it, so the defaults is useless. I did this, and now it works even without a config entry for the bundle.

**Comment by mostertb** [comment]
@sarelvdwalt  Thank you for the updated version. Going through your code, would I be correct in saying that the `console_stream` configuration option that you've added currently doesnt do anything?

**Comment by sarelvdwalt** [comment]
@mostertb yes, that's correct - we'll have to flesh that out, but I figured I'd add the config entries so we know where and how to build it later on

**Pull request merged**
