### PR TITLE
Handle input options in console event instead of configure method

### PR DESCRIPTION
**Pull request by pierredup**
Currently when extending the `BaseCommand` class and overwriting the `configure` method, you need to call `parent::configure`, otherwise the parameters set by `BaseCommand` won't be set.

This change moves the input definition into an event when the command runs. This means that you no longer have to worry about calling `parent::configure`, the definition will always be set if you extend `BaseCommand`.

A side-effect is that the `RutimeConfig` needs to move to the constructer, since the `configure` is not overwritten anymore. This means the runtime config is always available, and some checks can be removed to check if it is set or not.

TODO:
- [x] Update unit tests

### CODE REVIEW

**Comment by mostertb** [comment]
Hi @pierredup 

I really like this change. This is exactly what we need here. I also need to give you a particular thumbs up for making sure that you covered the `HelpCommand` case!

I am happy with moving the initialisation of `RuntimeConfig` in to the constructor. I would go as far as saying that we should update `RuntimeConfig::PHASE_CONFIGURE` and `RuntimeConfig::PHASE_POST_CONFIGURE` to `RuntimeConfig::PHASE_CONSTRUCT` `RuntimeConfig::PHASE_POST_CONSTRUCT` respectively.
This approach has the added bonus that the constructor is less likely to be overridden with its parent not called. What do you think of updating the text of the check for the RuntimeConfig check to reflect that the constructor was not called to help anyone who tries to do something unusual? 

So you dont bash your head against the wall: While you are writing the tests, you may need to remove the cache files for the bundled test Application 
( `Tests/Fixtures/App/cache`). I need to create an issue for the fact that the test suite doesnt clear the cache. Its only been an issue for updating code that affects DI so far.

Lastly, I would be very interested in looking at doing a similar thing with the `initialize()` function to ensure it is called. If you are interested, feel free to open an issues to discuss it as it has some subtle issues.

**Comment by mostertb** [comment]
Issue #13 has been added to address the cache issue mentioned above

**Comment by pierredup** [comment]
Unit tests have been updated, as well as the RuntimeConfig constants

> What do you think of updating the text of the check for the RuntimeConfig check to reflect that the constructor was not called to help anyone who tries to do something unusual?

When a command doesn't call `parent::__construct()`, then Symfony will already bail out early ([Application.php#L395](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Console/Application.php#L395)).which means that the exception for the `RuntimeConfig` check won't ever be thrown. So IMO it's not necessary to keep those checks. But if you want it for an extra pre-caution, then I'll add them back. 

> Lastly, I would be very interested in looking at doing a similar thing with the initialize() function to ensure it is called. If you are interested, feel free to open an issues to discuss it as it has some subtle issues.

I have created issue #17 to start a discussion on this.

**Comment by mostertb** [comment]
Im very happy with this. Good job

You are right about the exception. Thanks for linking the Symfony code

I cant wait to see what you do with #17

**Pull request merged**
