### PR TITLE
Locking mechanism, with accompanying option and config.yml capabilities

### PR DESCRIPTION
**Pull request by sarelvdwalt**
One can now switch the locking mechanism on/off by default in the config:

``` yml
afrihost_base_command:
    locking:
        enabled:              true
```

On top of that, the enabling/disabling of locking can be switched on/off via a command line option: `--locking=on` or `--locking=off`.
And finally, to start off things better, I've built in validation for the option (and made a space for other validation in future) whereby if we specify something like `--locking=onnnn` it will fail on validation and stop the process, throwing a ValidatorException with an appropriate message.

### CODE REVIEW

**Comment by mostertb** [comment]
This is a very nice feature.

The validate function for input parameters is also a good step forward and something we need. It is possible for the initialise function to be overridden without calling the parent version. Something to think about (not for this PR) is a way to ensure that it is. There is a rudimentary check in `getLogger()` but we can do better than this.

Here are some general points:
- Is it an option to exit with an exception rather than the `exit()` function if the lock cannot be acquired so that other Symfony events and logging can be triggered?
- Can we add an equivalent of `setLogToConsole()` for locking so that the global default in the config file can be changed in an overridden initialise function. This will allow users to make a particular command always need a lock

**Comment by sarelvdwalt** [comment]
Ah, good point. I will:
- Throw a `UnableToAcquireLockException` instead of the exit() - we need to be careful that people are aware of this, so that this doesn't trigger a regq/aq failure
- I will add a `setLocking(boolean)` function - this does exactly what --locking=on/off does with true/false, but inside an overridable function

**Comment by sarelvdwalt** [comment]
Ok I have:
- [x] Implemented throwing of an exception instead of exit(). The exception is `LockAcquireException` (custom, in the Exceptions folder). 
  https://github.com/sarelvdwalt/BaseCommandBundle/commit/ea737b82724fe7e0a1f17d4e1917357e02a02a9a
- [x] Given us the ability to call `$this->setDefaultLocking(true);` or `$this->setDefaultLocking(false);` in the implementation class to override whatever was given in config.yml (or the bundle's default behaviour) 
  https://github.com/sarelvdwalt/BaseCommandBundle/commit/02b28844d5bca759d5d4647975d292408afb0c10

I believe this is now ready for merge ;)

**Comment by mostertb** [comment]
PR Merged. Thank you for the contribution.

The `setDefaultLocking()` function has little use after the `LockHandler` is initialised. Would you look at throwing an exception in this case as it will always be a logic error on the part of the user. 

Here is an example of setting the filename after the log handler is initialised:

``` PHP
    public function setLogFilename($logFilename)
    {
        if (!is_null($this->logger)) {
            throw new \Exception('Cannot set manual logfile name. Logger is already initialised');
        }

        $this->logFilename = $this->getContainer()->get('kernel')->getLogDir() . DIRECTORY_SEPARATOR . $logFilename;

        return $this;
    }
```

**Pull request merged**
