### PR TITLE
PHP Memory Limit configuration

### PR DESCRIPTION
**Pull request by sarelvdwalt**
**NB:** This is not complete with tests yet, I'd like to get feedback on this before I write tests to make sure we're thinking in the same direction.

I wanted to keep the configuration as close to what set_ini allows for 'memory_limit', which is integer for bytes, but shorthand is allowed, thus K, M, G and so on (1024 base)

Thus, the idea here is that the config looks something similar to below:

``` yaml
afrihost_base_command:
    memory_limit:  123M
```

3 states exist:
- No configuration overriding is done: The system will not touch the memory_limit ini setting, thus using whatever PHP is set to use
- Overwritten in config.yml: As above, it will be set to "123M" - which PHP will interpret at 123 MegaBytes (1024 base)
- Overwritten via the `$this->setMemoryLimit("256M")`: This will set the memory_limit to "256M" which PHP will interpret as 256 MebaBytes (1024 base)

Please give me your thoughts. If you're happy with this let me know and I'll write the tests and let you know when you can merge, otherwise I'll make the appropriate changes :)

### CODE REVIEW

**Comment by sarelvdwalt** [comment]
Alright, I believe this is ready for merge ;) @mostertb

**Comment by mostertb** [comment]
You have taken a good approach. This is looking very good. 
I particularly like that nothing is done if the config isnt present and that attempting to set the value after initialisation is logged.

Following from our offline discussion, the memory_limit setting is something that is often restricted in hardened or high-contention environments (such as shared hosting). We thus need to make the feature tolerant of this by both preventing  fatal errors and notifying the user when the function has no effect.
Some of the hardening situations that I have encountered include:
1. the `ini_set()` function has been made unavailable. This would be done via the `disable_functions` option in the `php.ini` . This situation will cause a fatal error but can be checked for with `function_exists()` 
2. PHP is executing in [safe mode](http://php.net/manual/en/features.safe-mode.php) which prevents the changing of the memory limit. This configuration is deprecated with 5.4. It also fails silently 
3. PHP is running with the Suhosin plugin with the [suhosin.memory_limit](http://suhosin.org/stories/configuration.html#suhosin-memory-limit) config set. This is very common in shared hosting as it defines an upper bound that the memory limit can be set to (with low values being allowed). This extension should be detectable with `extension_loaded('suhosin')`

There are very likely others. When setting the limit, we should thus:
- check for the `ini_set()` function being available
- check that it doesn't return false
- check that the memory limit has been set to what we tried to set it to. `ini_get ()` would be useful here

And then log any failures

On a completely different note, something to consider is that we currently have three php options that we want to configure (display_errors, error_reporting, memory_limit). What do you thing of moving our config option to a `php_setting` node 

E.G.

``` yaml
afrihost_base_command:
    php_setting:
        memory_limit:  123M
```

**Comment by mostertb** [comment]
Just had another idea. While you are working on this, give some though to a maximum execution time setting...

**Comment by sarelvdwalt** [comment]
Moved the memory_limit setting in configuration one level lower, below a 'php' heading:

``` yaml
afrihost_base_command:
    php:
        memory_limit:         ~
    locking:
        lock_file_folder:     null
        enabled:              true
    logger:
        handler_strategies:
            default:
                file_extention:       .log.txt
            console_stream:
                enabled:              true
```

**Comment by sarelvdwalt** [comment]
Hey, I'm going to do the max-execution-time in another PR. Let me know if there's something on this one that needs doing - I'll fork this branch for the max-execution-time ;)

**Comment by mostertb** [comment]
Thanks for moving the memory limit setting one level deeper. 

Will you please add the three checks that I detailed in my previous comment and then provide test coverage for the checks. 

Good idea to fork the max-execution-time feature from this branch - there is a lot of overlap in features. I have added this feature to the TODO for you

**Comment by sarelvdwalt** [comment]
Hey @mostertb 

I have updated the `setMemoryLimit()` function as far as I could. My comments on the bullet points below:
- check for the ini_set() function being available: This has been done, however the ability to switch said function off has been deprecated. This is thus only for legacy systems, and is largely untestable. No unit tests was added.
- check that it doesn't return false: I have not implemented this, as the test for whether the setting of memory limit was successful or not is sufficient to cover this.
- check that the memory limit has been set to what we tried to set it to. ini_get () would be useful here: This has been done. Also, because we cannot switch the ability of PHP to do this off anymore, this is largely untestable. No unit tests was added.

It is important to notice, that I have moved the actual setting of the ini value out of initialize and replaced that with running the setMemoryLimit function with whatever the private value is. If this is not done and handled by the function, then calling it after initialize fires is useless.

**Comment by mostertb** [comment]
Thank you for the the updates and feedback

**Pull request merged**
